-- MySQL Script generated by MySQL Workbench
-- 08/23/16 10:10:09
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`account` (
  `idaccount` INT NOT NULL AUTO_INCREMENT,
  `mail` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL,
  `firstname` VARCHAR(45) NULL,
  `dateinscription` DATETIME NOT NULL,
  `datelastconnection` DATETIME NOT NULL,
  `isban` TINYINT(1) NOT NULL DEFAULT 0,
  `avertissement` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idaccount`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`account` (
  `idaccount` INT NOT NULL AUTO_INCREMENT,
  `mail` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL,
  `firstname` VARCHAR(45) NULL,
  `dateinscription` DATETIME NOT NULL,
  `datelastconnection` DATETIME NOT NULL,
  `isban` TINYINT(1) NOT NULL DEFAULT 0,
  `avertissement` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idaccount`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`script`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`script` (
  `idscript` INT NOT NULL AUTO_INCREMENT,
  `script` VARCHAR(45) NULL,
  `lastupdate` VARCHAR(45) NULL,
  `isvalide` TINYINT(1) NOT NULL DEFAULT flase,
  PRIMARY KEY (`idscript`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`stickman`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`stickman` (
  `idstickman` INT NOT NULL AUTO_INCREMENT,
  `idaccount` INT NOT NULL,
  `idscript` INT NOT NULL,
  `stickname` VARCHAR(45) NOT NULL,
  `countround` INT NULL,
  `countwin` INT NULL,
  `countlost` INT NULL,
  PRIMARY KEY (`idstickman`, `idaccount`, `idscript`),
  INDEX `fk_stickman_account1_idx` (`idaccount` ASC),
  INDEX `fk_stickman_script1_idx` (`idscript` ASC),
  CONSTRAINT `fk_stickman_account1`
    FOREIGN KEY (`idaccount`)
    REFERENCES `mydb`.`account` (`idaccount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stickman_script1`
    FOREIGN KEY (`idscript`)
    REFERENCES `mydb`.`script` (`idscript`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`item` (
  `iditem` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  `boost` INT NOT NULL,
  `price` FLOAT NOT NULL,
  PRIMARY KEY (`iditem`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`item_has_stickman`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`item_has_stickman` (
  `idstickman` INT NOT NULL,
  `iditem` INT NOT NULL,
  `datebuild` DATETIME NULL,
  `item_has_stickmancol` VARCHAR(45) NULL,
  PRIMARY KEY (`idstickman`, `iditem`),
  INDEX `fk_item_has_stickman_stickman1_idx` (`idstickman` ASC),
  INDEX `fk_item_has_stickman_item1_idx` (`iditem` ASC),
  CONSTRAINT `fk_item_has_stickman_item1`
    FOREIGN KEY (`iditem`)
    REFERENCES `mydb`.`item` (`iditem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_has_stickman_stickman1`
    FOREIGN KEY (`idstickman`)
    REFERENCES `mydb`.`stickman` (`idstickman`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`information`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`information` (
  `idinformation` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `date` VARCHAR(45) NOT NULL,
  `texte` TEXT(250) NOT NULL,
  PRIMARY KEY (`idinformation`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`arena`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`arena` (
  `idarena` INT NOT NULL AUTO_INCREMENT,
  `idstickmanwinner` INT NOT NULL,
  `datecreate` DATETIME NULL,
  PRIMARY KEY (`idarena`, `idstickmanwinner`),
  INDEX `fk_arena_stickman1_idx` (`idstickmanwinner` ASC),
  CONSTRAINT `fk_arena_stickman1`
    FOREIGN KEY (`idstickmanwinner`)
    REFERENCES `mydb`.`stickman` (`idstickman`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
